from enum import Enum


class EntityType(Enum):
    COMPONENT = "COMPONENT"
    SYMPTOM = "SYMPTOM"
    ERROR_CODE = "ERROR_CODE"
    SOLUTION = "SOLUTION"
    DEVICE = "DEVICE"
    FAULT_MODE = "FAULT_MODE"
    WORK_ORDER = "WORK_ORDER"
    CAUSE = "CAUSE"


class RelationType(Enum):
    CAUSES = "CAUSES"
    BELONGS_TO = "BELONGS_TO"
    RESOLVES = "RESOLVES"
    DIAGNOSES = "DIAGNOSES"
    HAS_FAULT = "HAS_FAULT"
    ROOT_CAUSE_OF = "ROOT_CAUSE_OF"
    TREATED_BY = "TREATED_BY"
    RECORDED_IN = "RECORDED_IN"
